name: CI/CD Pipeline - User Service

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm test # Ejecución de pruebas exhaustivas
    - name: Build Docker Image
      run: docker build -t user-service-api .
